---
# _source: http://amobiz.github.io/2015/12/21/applying-eslint-using-atom-linter-eslint/
root: true
env:
  browser: true
  commonjs: true
  es6: true
  node: true
# globals:
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  sourceType: module
plugins:
  - react
rules:
  react/no-deprecated: 0
  react/prop-types: 0
  no-console: off
  no-unused-vars:
  - warn
  - vars: all
    args: after-used
  indent:
  - error
  - 2
  linebreak-style:
  - error
  - unix
  quotes:
  - warn
  - single
  semi:
  - error
  - never
